### ISSUE TITLE
Pathfinder binary takes very long to return steps

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-transfer#13]
The pathfinder binary takes very long to return steps for some transactions, which makes the API to timeout. (The API timeout has been increased already)
The same binary in a local computer sometimes takes only half of the amount of time. 

This translates in Myxogastria to show to the users the message "Max amount cannot be calculated"

Some examples to reproduce the issue:
```./pathfinder --flowcsv  0x3BF71eAa5589A84F7F440aacd2f7B9718D1c53c5  0x83A1CFECc252AF00B8ca7824bcd1381a2A1BBD05 200000000000000000000 edges.csv```

In local computer these are the results:
``Took 161.038```
In the droplet itself
```Took 227.461```

` ./pathfinder --flowcsv  0x239Ae91De9De27De6E031E35f7eb07E4e918002a  0x9BA1Bcd88E99d6E1E03252A70A63FEa83Bf1208c 5600000000000000000000 edges.csv`
    in my comp: ```Max flow 15921918337626142796588 using 1301 nodes/edges
Took 80.7861```
    in the pathfinder from the pod: ```Max flow 16622758285646291338079 using 1295 nodes/edges
Took 156.043``

**Comment by llunaCreixent** [comment]
Solved by upgrading to pathfinder2
